framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(ADMIN_EMAIL)%'
        headers:
            from: '%env(BRAND_EMAIL)%'
            bcc: '%env(ADMIN_EMAIL)%'
