parameters:
    env(MASSIVE_SEARCH_PREFIX): 'massive'

massive_search:
    metadata:
        prefix: '%env(resolve:MASSIVE_SEARCH_PREFIX)%'
    adapter: elastic
    adapters:
        elastic:
            version: 7.2
            hosts:
                - '%env(resolve:ELASTICSEARCH_HOST)%'
