framework:
    messenger:
        default_bus: messenger.command.bus
        #failure_transport: failed

        buses:
            messenger.command.bus:
                default_middleware: false
                middleware:
                    - handle_message

            messenger.query.bus:
                default_middleware: false
                middleware:
                    - handle_message

        transports:
            sync: 'sync://'
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
        # Route your messages to the transports
        # 'App\Message\YourMessage': async
