# Security should be configured for website in `security_website.yaml` and for admin in `security_admin.yaml`
security:
  access_decision_manager:
    strategy: unanimous
    allow_if_all_abstain: true

  encoders:
    Sulu\Bundle\SecurityBundle\Entity\User: bcrypt
    App\Entity\User: bcrypt

  providers:
    # Admin
    sulu:
      id: sulu_security.user_provider

    # Website
    app_user_provider:
      id: App\Security\UserProvider

  access_control:
    # Admin
    - { path: ^/admin/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/security/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/_wdt, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/translations, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, roles: ROLE_USER }

    # Website
    - { path: ^/api/auth/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/user/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

  firewalls:
    # Development
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # Admin
    admin:
      pattern: ^/
      anonymous: true
      lazy: true
      provider: sulu
      entry_point: sulu_security.authentication_entry_point
      json_login:
        check_path: sulu_admin.login_check
        success_handler: sulu_security.authentication_handler
        failure_handler: sulu_security.authentication_handler
      logout:
        path: sulu_admin.logout
        success_handler: sulu_security.logout_success_handler

    # Website
    doc:
      pattern: ^/api/docs
      stateless: true
      anonymous: true

    refresh:
      pattern:  ^/api/auth/refresh
      provider: app_user_provider
      stateless: true
      anonymous: true

    register:
      pattern:  ^/api/auth/register
      stateless: true
      anonymous: true

    password_reset:
      pattern: ^/api/auth/password-reset
      stateless: true
      anonymous: true

    login:
      pattern: ^/api/auth/login
      stateless: true
      anonymous: true
      json_login:
        provider: app_user_provider
        check_path: /api/auth/login
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#firewalls-authentication

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true

    main:
      anonymous: true
      lazy: true

sulu_security:
  checker:
    enabled: true

sulu_core:
  locales:
    en: English
    nl: Nederlands
  translations:
    - en
    - nl