# To enable security bundle for website you need to change `config/bundles.php` file
#security:
#    encoders:
#        Sulu\Bundle\SecurityBundle\Entity\User: bcrypt
#
#    providers:
#        sulu:
#            id: sulu_security.user_provider
#
#    firewalls:
#        website:
#            pattern: ^/
#            anonymous: lazy
#            # The login and logout routes need to be created.
#            # For an advanced user management with registration and opt-in emails have a look at the:
#            # https://github.com/sulu/SuluCommunityBundle
#            form_login:
#                login_path: login
#                check_path: login
#            logout:
#                path: logout
#                target: /
#            remember_me:
#                secret:   "%kernel.secret%"
#                lifetime: 604800 # 1 week in seconds
#                path:     /
#
#sulu_security:
#    checker:
#        enabled: true
