sentry:
    dsn: '%env(SENTRY_DSN)%'
    register_error_listener: false # Disables the ErrorListener
    messenger:
        enabled: true # flushes Sentry messages at the end of each message handling
        capture_soft_fails: true # captures exceptions marked for retry too
    options:
        environment: '%kernel.environment%'
        release: '%env(APP_VERSION)%'

monolog:
    handlers:
        sentry:
            type: sentry
            level: !php/const Monolog\Logger::NOTICE
            hub_id: Sentry\State\HubInterface
