snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
    session:
        client: default
        ttl: 604800
        prefix: su_session_
