sulu_form:
    mail:
        from: "%env(SULU_ADMIN_EMAIL)%"
        to: "%env(SULU_ADMIN_EMAIL)%"
        sender: "%env(SULU_ADMIN_EMAIL)%"
    dynamic_lists:
        sulu_page.page_edit_form:
            form:
                template: form
                property: form
                type: page
    dynamic_disabled_types:
        #- firstName
        #- lastName
    honeypot:
        field: "Honey Honey Honey"
        strategy: no_save

framework:
    esi: true
    fragments: true