sulu_admin:
    email: "%env(ADMIN_EMAIL)%"
    forms:
        directories:
            - "%kernel.project_dir%/config/forms"
    lists:
        directories:
            - "%kernel.project_dir%/config/lists"

    # Registering Sulu Resources in this section
    resources:
        publications:
            routes:
                list: app.get_publications
                detail: app.get_publication

sulu_core:
    locales:
        nl: Nederlands
        en: English
    translations:
        - nl
        - en
    fallback_locale: nl