mysqldb:
  type: mysql:10.4
  disk: 512

cacheredis:
  type: redis:6.0
  configuration:
    # https://docs.platform.sh/configuration/services/redis.html#eviction-policy
    maxmemory_policy: volatile-lru

# If you wish to have a separate Redis instance for sessions, uncomment
# this service and the corresponding relationship in .platform.app.yaml.
#redissession:
#    type: 'redis:5.0'
#    configuration:
#        maxmemory_policy: allkeys-lru

searchelastic:
  type: elasticsearch:7.9
  disk: 256

# Do not change the service name to something different than 'varnish'
varnish:
  type: 'varnish:6.0'
  relationships:
    app: "app:http"
  configuration:
    vcl: !include
      type: string
      path: varnish.vcl