name: Symfony Build

on:
  push:
  pull_request:

jobs:
  php:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.0']
        composer-versions: ['composer:v1']
      fail-fast: false

    name: PHP ${{ matrix.php-versions }} @ ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          tools: ${{ matrix.composer-versions }}
          extensions: xdebug, mbstring, posix

      - name: Check versions
        run: |
          php -v
          php -m
          composer --version
        working-directory: symfony

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-suggest
        working-directory: symfony

      - name: Run tests
        run: php vendor/bin/grumphp run --no-interaction
        working-directory: symfony